// Generated by scripts/sync-tokens-native.mjs from tests/figma-tokens.json (Okara Design System, Figma
// 7glNMA9d7iVJFf2CvyrzAb). Do not edit by hand: change Figma, update the JSON, run the script.

export const primitive = {
  "neutralPage": "#eef5f4",
  "neutralSurface": "#ffffff",
  "neutralSurfaceSecondary": "#efeee5",
  "neutralInk": "#16150f",
  "neutralInkMedium": "#747167",
  "neutralInkMuted": "#928e80",
  "neutralBorder": "#16150f",
  "brandIndigo": "#4f46e5",
  "brandIndigo800": "#1f17a7",
  "brandIndigo900": "#080095",
  "brandIndigo950": "#06006c",
  "brandIndigoMid": "#756dff",
  "brandIndigoLight": "#908af6",
  "brandIndigoPale": "#f5f5ff",
  "brandMint": "#13d075",
  "brandMintDeep": "#00904b",
  "dataGreen": "#17a768",
  "dataLime": "#cdd936",
  "dataRedOrange": "#e2583a",
  "dataRed": "#a12a2f",
  "dataOchre": "#a89412",
  "brandMintLight": "#7be9b4",
  "dataPurpleVivid": "#4b0fa5",
  "dataCyan": "#1dc0bb",
  "dataBlue": "#2285bb",
  "dataPink": "#e3029f",
  "statusGreenDeep": "#0a6d42",
  "neutralCharcoal800": "#32312c",
  "neutralCharcoal900": "#1f1e19",
  "neutralStone50": "#efeee5",
  "neutralStone100": "#e4e3da",
  "statusRedDeep": "#bd0007",
  "neutralStone150": "#deddd4",
  "neutralStone300": "#cbcac5",
  "neutralStone325": "#cac9c0",
  "neutralStone350": "#acaca1",
  "statusOchreDeep": "#7a5703",
  "dataOrange": "#ffba3a",
  "statusGreenPale": "#e3f4ec",
  "statusRedPale": "#ffc4c6",
  "neutralStone400": "#aaa698",
  "neutralStone500": "#969284",
  "statusYellowPale": "#ffe9b7",
  "neutralOffWhite": "#f9f9f7",
  "dataGreenLight": "#76c8a4",
  "neutralSurfaceTransparent": "#ffffff00",
  "neutralOffWhiteTransparent": "#f9f9f700"
} as const;

export const color = {
  "surfacePrimary": "#ffffff",
  "surfaceSecondary": "#efeee5",
  "textPrimary": "#16150f",
  "textSecondary": "#747167",
  "textMuted": "#969284",
  "borderDefault": "#cbcac5",
  "borderSecondary": "#efeee5",
  "actionPrimary": "#16150f",
  "actionPrimaryHover": "#32312c",
  "actionPrimaryPress": "#1f1e19",
  "actionSecondary": "#ffffff",
  "actionSecondaryHover": "#e4e3da",
  "actionSecondaryPress": "#deddd4",
  "actionSecondaryActive": "#cac9c0",
  "actionDisable": "#969284",
  "actionAccent": "#4f46e5",
  "actionAccentHover": "#908af6",
  "actionAccentPress": "#1f17a7",
  "actionAccentDisable": "#756dff",
  "actionDestructive": "#bd0007",
  "linkDefault": "#4f46e5",
  "linkHover": "#080095",
  "linkPress": "#1f17a7",
  "linkDisable": "#756dff",
  "dataPurple": "#4b0fa5",
  "dataBlue": "#2285bb",
  "dataLightBlue": "#1dc0bb",
  "dataPink": "#e3029f",
  "dataLime": "#cdd936",
  "borderHover": "#acaca1",
  "borderTertiary": "#32312c",
  "borderFocus": "#4f46e5",
  "borderSelectedItem": "#908af6",
  "borderDark": "#16150f",
  "borderDestructive": "#bd0007",
  "textWhite": "#ffffff",
  "textAccent": "#4f46e5",
  "textAccentLight": "#756dff",
  "surfaceTertiary": "#747167",
  "surfaceBody": "#f9f9f7",
  "surfaceAccent": "#4f46e5",
  "surfaceAccentDark": "#080095",
  "surfaceAccentDeep": "#06006c",
  "surfaceAccentLight": "#f5f5ff",
  "surfaceDark": "#16150f",
  "surfaceSuccess": "#e3f4ec",
  "surfaceFail": "#ffc4c6",
  "surfaceWarning": "#ffe9b7",
  "dataOrange": "#ffba3a",
  "statusSuccess": "#0a6d42",
  "statusFail": "#a12a2f",
  "statusWarning": "#7a5703",
  "surfacePrimaryTransparent": "#ffffff00",
  "surfaceBodyTransparent": "#f9f9f700"
} as const;

export const space = {
  "tn": 4,
  "xs": 8,
  "sm": 12,
  "md": 16,
  "lg": 24,
  "xl": 40,
  "2xl": 48,
  "3xl": 80,
  "navPaddingY": 8,
  "controlGap": 12,
  "tagsIndent": 56
} as const;

export const radius = {
  "ty": 4,
  "sm": 8,
  "md": 16,
  "lg": 24,
  "full": 999,
  "card": 20
} as const;

export const opacity = {
  "disabled": 0.4,
  "background": 0.24
} as const;

export const text = {
  "DisplayTitle": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 40,
    "lineHeight": 48
  },
  "ValueXL": {
    "fontFamily": "MartianMono_500Medium",
    "fontSize": 32
  },
  "ValueLarge": {
    "fontFamily": "MartianMono_500Medium",
    "fontSize": 16
  },
  "ValueMedium": {
    "fontFamily": "MartianMono_500Medium",
    "fontSize": 14,
    "letterSpacing": -0.56
  },
  "ValueSmall": {
    "fontFamily": "MartianMono_500Medium",
    "fontSize": 12,
    "letterSpacing": -0.48
  },
  "HeadingXL": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 24,
    "lineHeight": 24
  },
  "HeadingLarge": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 20,
    "lineHeight": 24
  },
  "HeadingMedium": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 16,
    "lineHeight": 16
  },
  "HeadingSmall": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 14,
    "lineHeight": 14
  },
  "BodyLargeMedium": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 16,
    "lineHeight": 20,
    "letterSpacing": -0.32
  },
  "BodyLargeSemiBold": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 16,
    "lineHeight": 20,
    "letterSpacing": -0.32
  },
  "BodyMediumRegular": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 14,
    "lineHeight": 16,
    "letterSpacing": -0.28
  },
  "BodyMediumMedium": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 14,
    "lineHeight": 16,
    "letterSpacing": -0.28
  },
  "BodyMediumSemiBold": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 14,
    "lineHeight": 16,
    "letterSpacing": -0.28
  },
  "BodySmallRegular": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 12,
    "lineHeight": 14,
    "letterSpacing": -0.24
  },
  "BodySmallMedium": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 12,
    "lineHeight": 14,
    "letterSpacing": -0.24
  },
  "BodySmallSemiBold": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 12,
    "lineHeight": 14,
    "letterSpacing": -0.24
  },
  "LabelDefaultSemiBold": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 12,
    "lineHeight": 12,
    "letterSpacing": 0.24
  },
  "LabelDefaultMedium": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 12,
    "lineHeight": 12,
    "letterSpacing": -0.24
  },
  "LabelTinyRegular": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 10,
    "lineHeight": 10
  },
  "LabelTinySemiBold": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 10,
    "lineHeight": 10,
    "letterSpacing": -0.2
  },
  "LabelTinyMedium": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 10,
    "lineHeight": 10,
    "letterSpacing": -0.2
  },
  "BadgeSemiBolt": {
    "fontFamily": "DMSans_500Medium",
    "fontSize": 8,
    "lineHeight": 8,
    "letterSpacing": -0.16
  }
} as const;

