// Generated by scripts/sync-tokens-native.mjs from tests/figma-tokens.json (Okara Design System, Figma
// 7glNMA9d7iVJFf2CvyrzAb). Do not edit by hand: change Figma, update the JSON, run the script.

export const primitive = {
  "neutralPage": "#eef5f4ff",
  "neutralSurface": "#ffffffff",
  "neutralSurfaceSecondary": "#efeee5ff",
  "neutralInk": "#16150fff",
  "neutralInkMedium": "#747167ff",
  "neutralInkMuted": "#928e80ff",
  "neutralBorder": "#16150fff",
  "brandIndigo": "#4f46e5ff",
  "brandMint": "#13d075ff",
  "brandMintDeep": "#00904bff",
  "dataGreen": "#17a768ff",
  "dataRedOrange": "#e2583aff",
  "dataRed": "#a12a2fff",
  "dataOchre": "#a89412ff",
  "neutralStone400": "#aaa698ff",
  "neutralStone300": "#cbcac5ff",
  "brandMintLight": "#7be9b4ff",
  "dataPurpleVivid": "#4b0fa5ff",
  "dataCyan": "#1dc0bbff",
  "dataBlue": "#2285bbff",
  "dataPink": "#e3029fff",
  "statusGreenDeep": "#0a6d42ff",
  "neutralCharcoal800": "#32312cff",
  "neutralCharcoal900": "#1f1e19ff",
  "neutralStone100": "#e4e3daff",
  "neutralStone150": "#deddd4ff",
  "neutralStone350": "#acaca1ff",
  "statusOchreDeep": "#7a5703ff",
  "brandIndigoLight": "#908af6ff",
  "dataOrange": "#ffba3aff",
  "statusGreenPale": "#e3f4ecff",
  "statusRedPale": "#fd8a8dff",
  "statusYellowPale": "#ffe9b7ff",
  "brandIndigo900": "#080095ff",
  "brandIndigo800": "#1f17a7ff",
  "brandIndigoPale": "#f5f5ffff",
  "neutralOffWhite": "#f9f9f7ff",
  "neutralStone325": "#cac9c0ff",
  "brandIndigoMid": "#756dffff",
  "statusRedDeep": "#bd0007ff",
  "dataLime": "#cdd936ff",
  "brandIndigo950": "#06006cff",
  "neutralStone50": "#efeee5ff",
  "neutralStone500": "#969284ff",
  "dataGreenLight": "#76c8a4ff",
  "neutralSurfaceTransparent": "#ffffff00",
  "neutralOffWhiteTransparent": "#f9f9f700",
  "brandIndigoBright": "#c2bcffff",
  "darkBody": "#161713ff",
  "darkPrimary": "#1f201aff",
  "darkSecondary": "#2a2b24ff",
  "darkTertiary": "#35362eff",
  "darkText": "#f4f3eaff",
  "darkSecondaryText": "#c6c4b8ff",
  "darkMuted": "#a6a395ff",
  "darkBorder": "#55564bff",
  "darkHoverBorder": "#7d7e70ff",
  "darkSubtleBorder": "#3c3d34ff",
  "darkPrimaryAction": "#f4f3eaff",
  "darkPrimaryHover": "#deddcfff",
  "darkPrimaryPress": "#c8c6b7ff",
  "darkDisabled": "#77786bff",
  "darkAccentText": "#c2bcffff",
  "darkAccentHover": "#d6d1ffff",
  "darkAccentPress": "#aba2ffff",
  "darkAccentMuted": "#aaa2deff",
  "darkAccentSurface": "#292445ff",
  "darkAccentDeep": "#1f1a38ff",
  "darkSuccess": "#7de0a9ff",
  "darkSuccessSurface": "#18382bff",
  "darkDanger": "#ff9ea7ff",
  "darkDangerSurface": "#43242aff",
  "darkWarning": "#f3d17cff",
  "darkWarningSurface": "#3d331cff",
  "darkPurple": "#b18affff",
  "darkBlue": "#6cbfefff",
  "darkCyan": "#63dbd5ff",
  "darkPink": "#ff80cdff",
  "darkOrange": "#ffca70ff",
  "darkLime": "#d3df61ff",
  "darkMint": "#42d98fff",
  "darkMintSurface": "#204334ff",
  "darkRedOrange": "#ff9877ff",
  "darkInverse": "#16150fff",
  "darkPrimaryTransparent": "#1f201a00",
  "darkBodyTransparent": "#13141000",
  "darkColor": "#ffffffff",
  "brandMintPress": "#12b86bff",
  "brandMintInk": "#007a40ff",
  "brandMintInkHover": "#006535ff",
  "brandMintInkPress": "#004f2aff",
  "brandMintMuted": "#568b70ff",
  "darkMintMuted": "#729d85ff",
  "neutralBlack": "#000000ff",
  "statusRedMedium": "#d74c51ff",
  "notificationOrange": "#ea6b39ff",
  "notificationOrangeLight": "#f48c63ff",
  "notificationOrangePale": "#f9af92ff"
} as const;

export const color = {
  "surfacePrimary": "#ffffffff",
  "surfaceSecondary": "#efeee5ff",
  "textPrimary": "#16150fff",
  "textSecondary": "#747167ff",
  "textMuted": "#969284ff",
  "borderDefault": "#cbcac5ff",
  "actionPrimary": "#16150fff",
  "actionSecondary": "#ffffffff",
  "surfaceAccent": "#4f46e5ff",
  "dataLime": "#cdd936ff",
  "dataPurple": "#4b0fa5ff",
  "dataLightBlue": "#1dc0bbff",
  "dataBlue": "#2285bbff",
  "dataPink": "#e3029fff",
  "statusSuccess": "#0a6d42ff",
  "statusFail": "#a12a2fff",
  "actionPrimaryHover": "#32312cff",
  "actionPrimaryPress": "#1f1e19ff",
  "actionSecondaryHover": "#e4e3daff",
  "actionSecondaryPress": "#cbcac5ff",
  "borderHover": "#acaca1ff",
  "borderFocus": "#4f46e5ff",
  "textWhite": "#ffffffff",
  "surfaceTertiary": "#747167ff",
  "actionAccent": "#4f46e5ff",
  "statusWarning": "#7a5703ff",
  "actionAccentHover": "#908af6ff",
  "textAccent": "#4f46e5ff",
  "borderDark": "#16150fff",
  "surfaceDark": "#16150fff",
  "dataOrange": "#ffba3aff",
  "surfaceSuccess": "#e3f4ecff",
  "surfaceFail": "#fd8a8dff",
  "surfaceWarning": "#ffe9b7ff",
  "actionDisable": "#969284ff",
  "linkDefault": "#4f46e5ff",
  "linkHover": "#080095ff",
  "linkPress": "#1f17a7ff",
  "actionDestructive": "#bd0007ff",
  "surfaceAccentLight": "#f5f5ffff",
  "surfaceBody": "#f9f9f7ff",
  "actionSecondaryActive": "#e4e3daff",
  "actionAccentDisable": "#756dffff",
  "textAccentLight": "#756dffff",
  "linkDisable": "#756dffff",
  "actionAccentPress": "#1f17a7ff",
  "surfaceAccentDark": "#080095ff",
  "surfaceAccentDeep": "#06006cff",
  "borderDestructive": "#bd0007ff",
  "borderSecondary": "#efeee5ff",
  "borderTertiary": "#32312cff",
  "borderSelectedItem": "#908af6ff",
  "surfacePrimaryTransparent": "#ffffff00",
  "surfaceBodyTransparent": "#f9f9f700",
  "borderWarning": "#debba0ff",
  "borderDanger": "#e58d90ff",
  "surfaceMobileNavBg": "#ffffffff",
  "actionTertiaryHover": "#efeee5ff",
  "actionTertiaryPress": "#cbcac5ff",
  "actionTertiaryActive": "#e4e3daff",
  "textOnPrimary": "#ffffffff",
  "iconPrimary": "#16150fff",
  "surfaceTrack": "#cac9c0ff",
  "brandIndigo": "#4f46e5ff",
  "brandMint": "#13d075ff",
  "brandMintLight": "#7be9b4ff",
  "statusGreenPale": "#e3f4ecff",
  "statusGreenDeep": "#0a6d42ff",
  "statusRedDeep": "#bd0007ff",
  "dataRedOrange": "#e2583aff",
  "effectShadow868259160": "#16150f29",
  "effectShadow86825980": "#16150f14",
  "surfacePage": "#eef5f4ff",
  "surfaceCover": "#f7f6f1ff",
  "iconMuted": "#969284ff",
  "badgeCounterPressedBackground": "#1f1e19ff",
  "badgeCounterPressedText": "#ffffffff",
  "badgeCounterPressedBorder": "#16150fff",
  "surfaceMobileNavButtomBg": "#f5f5ffff",
  "surfaceMobileNavButtomIcon": "#4f46e5ff",
  "logoIndigo": "#4f46e5ff",
  "logoMint": "#13d075ff",
  "iconSecondary": "#747167ff",
  "iconLight": "#ffffffff",
  "textNotification": "#ea6b39ff",
  "borderNotification": "#f48c63ff"
} as const;

export const space = {
  "tn": 4,
  "xs": 8,
  "md": 16,
  "lg": 24,
  "xl": 40,
  "2xl": 48,
  "sm": 12,
  "3xl": 80,
  "navPaddingY": 8,
  "controlGap": 12,
  "tagsIndent": 56
} as const;

export const radius = {
  "sm": 8,
  "md": 16,
  "lg": 24,
  "full": 999,
  "ty": 4,
  "card": 20
} as const;

export const opacity = {
  "disabled": 0.4,
  "background": 0.24
} as const;

export const text = {
  "DisplayTitle": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 40
  },
  "DisplayTitleMobile": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 32
  },
  "ValueXL": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 32
  },
  "ValueLarge": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 16
  },
  "ValueMedium": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 14,
    "letterSpacing": -0.56
  },
  "ValueSmall": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 12,
    "letterSpacing": -0.48
  },
  "HeadingXL": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 24
  },
  "HeadingLarge": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 20,
    "letterSpacing": -0.4
  },
  "HeadingMedium": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 16,
    "letterSpacing": -0.32
  },
  "HeadingSmall": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 14,
    "letterSpacing": -0.28
  },
  "BodyLargeMedium": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 16,
    "letterSpacing": -0.32
  },
  "BodyLargeSemiBold": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 16,
    "letterSpacing": -0.32
  },
  "BodyMediumRegular": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 14,
    "letterSpacing": -0.28
  },
  "BodyMediumMedium": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 14,
    "letterSpacing": -0.28
  },
  "BodyMediumSemiBold": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 14,
    "letterSpacing": -0.28
  },
  "BodySmallRegular": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 12,
    "letterSpacing": -0.24
  },
  "BodySmallMedium": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 12,
    "letterSpacing": -0.24
  },
  "BodySmallSemiBold": {
    "fontFamily": "DMSans_600SemiBold",
    "fontSize": 12,
    "letterSpacing": -0.24
  },
  "BadgeSemiBolt": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 8,
    "letterSpacing": -0.16
  },
  "LabelLarge": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 18,
    "letterSpacing": -0.36
  },
  "LabelMedium": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 16,
    "letterSpacing": -0.32
  },
  "LabelSmall": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 16,
    "letterSpacing": -0.32
  },
  "LabelTiny": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 14,
    "letterSpacing": -0.28
  },
  "LabelMicro": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 12,
    "letterSpacing": -0.24
  },
  "LabelNano": {
    "fontFamily": "DMSans_400Regular",
    "fontSize": 10,
    "letterSpacing": -0.2
  }
} as const;

