// Writes the Okara Design System variables (tests/figma-tokens.json, read from Figma) into the token block of
// src/ui/okara.css, between the @tokens:start / @tokens:end markers. Run after updating the JSON from Figma.
//   node scripts/sync-tokens.mjs
// Names mirror Figma: Color/surface/primary -> --surface-primary, Spacing/space/xs -> --space-xs.
// Primitives get a --primitive- prefix (their names overlap the Color ones, e.g. data/blue) and the Color
// variables point at them with var(), exactly as the aliases in Figma do.
import { readFileSync, writeFileSync } from 'node:fs';

const tokens = JSON.parse(readFileSync(new URL('../tests/figma-tokens.json', import.meta.url), 'utf8'));
const cssPath = new URL('../src/ui/okara.css', import.meta.url);
const kebab = (name) => name.toLowerCase().replace(/\//g, '-');
export const cssName = (collection, name) => (collection === 'Primitives' ? '--primitive-' : '--') + kebab(name);
// Typography variables hold a family name only; the CSS adds a fallback stack after it.
export const FONT_FALLBACK = {
  'font/sans': 'system-ui, -apple-system, "Segoe UI", sans-serif',
  'font/mono': 'ui-monospace, SFMono-Regular, Menlo, monospace',
};
// Surface (Sept 29) holds spacing, radius and the text sizes / line heights in two modes. The page gets the Desktop
// values in :root and the Mobile values under MOBILE_QUERY (the same 640px the phone layout uses).
export const MOBILE_QUERY = '(max-width:640px)';
export const surfaceValue = (v) => v + 'px';
// Text styles (Figma local text styles) become four custom properties each:
// Body/Small/Medium -> --type-body-small-medium-size / -weight / -lh / -ls. Size and line height point at the Surface
// variables the style is bound to, so they follow the mode; letter spacing is a % in Figma, em here.
// Felipe (Oct 3): Figma's "Medium" (500) renders as 400 in code, for every text style.
export const codeWeight = (w) => (Number(w) === 500 ? 400 : Number(w));
export const textStyleVars = (name, t) => {
  const k = '--type-' + kebab(name);
  return [[k + '-size', t.sizeVar ? `var(${cssName('Surface', t.sizeVar)})` : t.size + 'px'], [k + '-weight', String(codeWeight(t.weight))],
    [k + '-lh', t.lhVar ? `var(${cssName('Surface', t.lhVar)})` : 'normal'], [k + '-ls', t.letterSpacing ? t.letterSpacing / 100 + 'em' : '0']];
};
export const fontStack = (name, family) => `"${family}", ${FONT_FALLBACK[name] || 'sans-serif'}`;


const lines = ['    /* Generated by scripts/sync-tokens.mjs from tests/figma-tokens.json. Do not edit by hand. */'];
for (const [collection, vars] of Object.entries(tokens)) {
  if (collection.startsWith('_')) continue;
  lines.push('', `    /* Collection: ${collection}${collection === 'Surface' ? ' (Desktop mode; Mobile below)' : ''} */`);
  if (collection === 'TextStyles') {
    for (const [name, t] of Object.entries(vars)) for (const [k, v] of textStyleVars(name, t)) lines.push(`    ${k}: ${v};`);
    continue;
  }
  for (const [name, value] of Object.entries(vars)) {
    let v;
    if (collection === 'Surface') v = surfaceValue(value.Desktop);
    else if (value && typeof value === 'object' && value.alias) v = `var(${cssName('Primitives', value.alias)})`;
    else if (typeof value === 'number') v = collection === 'Opacity' ? String(value > 1 ? value / 100 : value) : String(value);
    else if (collection === 'Typography') v = fontStack(name, value);
    else v = value;
    const note = collection === 'Opacity' && typeof value === 'number' && value > 1 ? '   /* Figma stores this one as a percentage (24) */' : '';
    lines.push(`    ${cssName(collection, name)}: ${v};${note}`);
  }
}
const mobile = ['  /* Generated by scripts/sync-tokens.mjs: the Surface collection in its Mobile mode. Do not edit by hand. */',
  `  @media ${MOBILE_QUERY}{`, '    :root{',
  ...Object.entries(tokens.Surface || {}).filter(([, v]) => v.Mobile !== v.Desktop).map(([name, v]) => `      ${cssName('Surface', name)}: ${surfaceValue(v.Mobile)};`),
  '    }', '  }'];
const replaceBetween = (css, a, b, body, indent) => {
  const i = css.indexOf(a), j = css.indexOf(b);
  if (i < 0 || j < 0) throw new Error(`markers ${a} / ${b} not found in okara.css`);
  return css.slice(0, i) + a + '\n' + body + '\n' + indent + css.slice(j);
};
let css = readFileSync(cssPath, 'utf8');
css = replaceBetween(css, '/* @tokens:start */', '/* @tokens:end */', lines.join('\n'), '    ');
css = replaceBetween(css, '/* @tokens-mobile:start */', '/* @tokens-mobile:end */', mobile.join('\n'), '  ');

// Oct 3 (Felipe): these components always use the Surface collection in its Mobile mode, whatever the surface around
// them (Figma: explicit mode Mobile on the component). Custom properties resolve where they are declared, so the block
// redeclares the Mobile Surface values AND every :root variable that reads them (text styles, --layout-* aliases...)
// on the component itself.
export const PINNED_MOBILE = [
  '.seg-tabs',                                   // Segment tab 4:166, Segments 30:98, Sub-segment tab 69:903, Sub-segments 69:900
  '.year-add-pill',                              // Add year 79:1242
  '.year-tabs', '.year-btn',                     // Nav tabs 59:850, Tab 53:801
  '.ds-input',                                   // Input 71:1093
  '.ds-dd', '.ds-dd-menu', '.ds-dd-item', '.date-dd', // Dropdown 71:1096 (the date field is one), dropdown-item 183:6858 (the menu is portaled)
  '.ds-notif', '.ds-notif-panel', '.ds-notif-page', '.ds-notif-item', // Notification 228:455, notification-item 228:469
  '.ds-app-header',                              // Product header 728:1445, App header 285:600
  '.ds-avatar',                                  // avatar 221:1044
  '.btn-pill', '.round-btn', '.ds-action-link',  // Button 41:119, Round button 52:629, Action link 607:1368 (Oct 3)
];
const rootCss = css.slice(0, css.indexOf('/* @tokens-mobile:start */'));
const decls = new Map();
for (const m of rootCss.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) decls.set(m[1], m[2].trim());
const surfaceNames = new Set(Object.keys(tokens.Surface || {}).map((n) => cssName('Surface', n)));
const dependent = new Set();
for (let grew = true; grew;) {
  grew = false;
  for (const [k, v] of decls) {
    if (surfaceNames.has(k) || dependent.has(k)) continue;
    const refs = [...v.matchAll(/var\((--[\w-]+)/g)].map((r) => r[1]);
    if (refs.some((r) => surfaceNames.has(r) || dependent.has(r))) { dependent.add(k); grew = true; }
  }
}
const pinned = ['  /* Generated by scripts/sync-tokens.mjs: components pinned to the Surface Mobile mode. Do not edit by hand. */',
  `  ${PINNED_MOBILE.join(', ')}{`,
  ...Object.entries(tokens.Surface || {}).map(([name, v]) => `    ${cssName('Surface', name)}: ${surfaceValue(v.Mobile)};`),
  ...[...dependent].map((k) => `    ${k}: ${decls.get(k)};`),
  '  }'];
css = replaceBetween(css, '/* @tokens-pinned:start */', '/* @tokens-pinned:end */', pinned.join('\n'), '  ');
writeFileSync(cssPath, css);
console.log(`okara.css: ${lines.filter((l) => l.includes(': ')).length} variables written, ${mobile.length - 6} Mobile overrides, ${pinned.length - 3} pinned declarations`);
