// node scripts/sync-icons.mjs [--check]
// Source: user-supplied Okara icon-family SVG exports, unchanged in public/icons/.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { svgMetadata, camel } from './svg-assets.mjs';
const root = new URL('../public/icons/', import.meta.url);
const files = readdirSync(root, { recursive: true }).filter(f => f.endsWith('.svg')).sort();
const entries = files.map(file => {
  const svg = readFileSync(new URL(file, root), 'utf8');
  const { width, height, hash } = svgMetadata(svg, file);
  const stem = file.replace(/\.svg$/, '').replace('@', 'At');
  const duplicate = stem.match(/^(.*)-(\d+)$/);
  let key = duplicate ? camel(duplicate[1]) + (Number(duplicate[2]) + 1) : camel(stem);
  key = ({ sEK: 'sek', qRCode: 'qrCode' })[key] || key;
  const name = key.replace(/[A-Z]/g, c => '-' + c.toLowerCase()).replace(/(\d+)$/, '-$1');
  key = ({ delete: 'deleteIcon', document: 'documentIcon', location: 'locationIcon' })[key] || key;
  // Family auto-layout uses 16px gaps. Security has 8px outer padding.
  // Seven older duplicate families place 20px before 16px and have no 24px variant.
  const order = width === 106 ? [10, 12, 20, 16] : width === 194 ? [10, 12, 16, 20, 24, 32] : [10, 12, 16, 20, 24];
  if (![106, 146, 162, 194].includes(width)) throw new Error(`${file}: inspect new family layout before syncing`);
  const padding = file === 'Security.svg' ? 8 : 0;
  let x = padding;
  const sizes = Object.fromEntries(order.map(size => {
    const frame = { viewBox: `${x} ${padding} ${size} ${size}` };
    x += size + 16;
    return [size, frame];
  }));
  if (x - 16 + padding !== width) throw new Error(`${file}: frame layout does not match export`);
  return { key, svg, data: { name, file, asset: `/icons/${file.split('/').map(encodeURIComponent).join('/')}?v=${hash}`, width, height, ...( /<path\b[^>]*fill="white"/.test(svg) ? { twoTone: true } : {} ), sizes } };
});
if (new Set(entries.map(e => e.key)).size !== entries.length) throw new Error('Duplicate icon export');
const header = '// Generated by scripts/sync-icons.mjs. Exact artwork lives in public/icons/.\n';
const output = header + entries.map(e => `export const ${e.key} = ${JSON.stringify(e.data)};`).join('\n') + '\n';
const nativeKeys = { home: 'home', user: 'user', plus: 'plus', arrowUp: 'arrowStraightUp' };
const native = Object.fromEntries(Object.entries(nativeKeys).map(([name, key]) => {
  const e = entries.find(e => e.key === key);
  return [name, { xml: e.svg.replaceAll('#16150F', 'currentColor'), sizes: e.data.sizes }];
}));
const outputs = [
  [new URL('../src/ui/icons.js', import.meta.url), output],
  [new URL('../mobile/src/components/iconAssets.ts', import.meta.url), header + `export const iconAssets = ${JSON.stringify(native)} as const;\n`],
];
for (const [path, content] of outputs) {
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`${path.pathname} is out of date`);
  } else writeFileSync(path, content);
}
console.log(`${entries.length} icon families ${process.argv.includes('--check') ? 'verified' : 'synced'}`);
