// Okara Color modes and styles, captured from Figma on Oct 7, 2026.
import { readFileSync, writeFileSync } from 'node:fs';
const tokens = JSON.parse(readFileSync(new URL('../src/ui/theme-tokens.json', import.meta.url), 'utf8'));
const name = (s) => '--' + s.replaceAll('/', '-');
const blocks = tokens.modes.map((mode, i) => `html[data-theme="${mode.name.toLowerCase()}"]{\n  color-scheme:${mode.name.toLowerCase()};\n` + tokens.colors.filter(row => typeof row[i + 1] === 'string').map(row => `  ${name(row[0])}:${row[i + 1]};`).join('\n') + '\n}');
const card = tokens.effects.find(e => e.name === 'Card').effects[0];
const c=card.color;
blocks.push(`:root{--card-shadow:${card.offset.x}px ${card.offset.y}px ${card.radius}px ${card.spread}px rgba(${Math.round(c.r*255)},${Math.round(c.g*255)},${Math.round(c.b*255)},${c.a.toFixed(2)});}`);
// Preserve Figma's gradient transform in object-bounding-box coordinates, at every card aspect ratio.
const paint=tokens.paints.find(p=>p.name==='Card body/Dark').paints[0];
const [[a,b,cx],[d,e,f]]=paint.gradientTransform, det=a*e-b*d;
const matrix=[e/det,-d/det,-b/det,a/det,(b*f-e*cx)/det,(d*cx-a*f)/det].join(' ');
const stops=paint.gradientStops.map(s=>`<stop offset="${s.position}" stop-color="rgb(${[s.color.r,s.color.g,s.color.b].map(v=>Math.round(v*255)).join(',')})" stop-opacity="${s.color.a}"/>`).join('');
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(${matrix})">${stops}</linearGradient></defs><rect width="1" height="1" fill="url(#g)"/></svg>`;
blocks.push(`:root{--card-body-dark:url("data:image/svg+xml,${encodeURIComponent(svg)}");}`);
writeFileSync(new URL('../src/ui/theme-generated.css', import.meta.url), '/* Generated by scripts/sync-theme.mjs. Source: Okara theme-tokens.json. */\n'+blocks.join('\n')+'\n');
